# Generated by Django 3.1.1 on 2020-09-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200914_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='active',
        ),
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='first',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
    ]
