# Generated by Django 3.1.1 on 2020-09-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200914_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocols',
            old_name='user_id',
            new_name='user',
        ),
    ]
